"""Coding platform architecture for Tangku AgentOS."""

from .interfaces import (
    CodingCoordinator,
    CodingConfiguration,
    CodingManagerInterface,
    CodingRegistryInterface,
    CodingSessionManager,
    CodingStatistics,
    CodeAnalyzer,
    CodeComparator,
    CodeEditor,
    CodeExplainer,
    CodeFormatter,
    CodeGenerator,
    CodeNavigator,
    CodeOptimizer,
    CodeRefactorManager,
    CodeReviewer,
    CodeSearchManager,
    CodeValidator,
    ProgrammingLanguageSupport,
    ProgrammingLanguageSupportRegistry,
)
from .manager import CodingManager
from .registry import CodingRegistry
from .intelligence import (
    CodeGraphManager,
    CodeIndexManager,
    CodeIntelligenceManager,
    SearchManager,
    StaticAnalysisManager,
    SymbolManager,
)
from .models import (
    CodingConfigurationModel,
    CodingSession,
    CodingStatisticsModel,
    ProgrammingLanguage,
    ProgrammingLanguageProfile,
)

__all__ = [
    "CodingManager",
    "CodingManagerInterface",
    "CodingCoordinator",
    "CodingSessionManager",
    "CodingRegistry",
    "CodingRegistryInterface",
    "CodingConfiguration",
    "CodingConfigurationModel",
    "CodingStatistics",
    "CodingStatisticsModel",
    "CodingSession",
    "ProgrammingLanguage",
    "ProgrammingLanguageProfile",
    "ProgrammingLanguageSupport",
    "ProgrammingLanguageSupportRegistry",
    "CodeAnalyzer",
    "CodeGenerator",
    "CodeEditor",
    "CodeRefactorManager",
    "CodeFormatter",
    "CodeReviewer",
    "CodeExplainer",
    "CodeNavigator",
    "CodeComparator",
    "CodeValidator",
    "CodeOptimizer",
    "CodeSearchManager",
    "CodeGraphManager",
    "CodeIndexManager",
    "CodeIntelligenceManager",
    "SearchManager",
    "StaticAnalysisManager",
    "SymbolManager",
]
