"""Provider runtime architecture for Tangku AgentOS."""

from importlib import import_module
from typing import Any

__all__ = [
    # Core Components
    "ProviderManager",
    "ProviderRegistry",
    "ProviderFactory",
    "ProviderAdapter",
    "ProviderSession",
    "ProviderHealth",
    "ProviderConfiguration",
    # Interfaces
    "ProviderRegistryInterface",
    "ProviderManagerInterface",
    "ProviderAdapterInterface",
    "ProviderFactoryInterface",
    "ProviderSessionInterface",
    "ProviderHealthInterface",
    # Integration
    "BaseProviderAdapter",
    "HTTPProviderAdapter",
    "ProviderCapabilityManager",
    "ProviderAuthenticationManager",
    "ProviderConfigurationLoader",
    "ProviderSessionManager",
    "ProviderConnectionManager",
    "ProviderRateLimitManager",
    "ProviderUsageManager",
    "ProviderStreamingManager",
    "ProviderRetryManager",
    "RetryManager",
    "RateLimiter",
    "CapabilityMatcher",
    "ProviderSelector",
    "ProviderRouter",
    "ProviderSelector",
    "FallbackManager",
    "LoadDistributionManager",
    "CostAwareRouter",
    "LatencyAwareRouter",
    "HealthAwareRouter",
    "ModelCatalogManager",
    # Hub
    "ProviderHub",
    # Dashboard
    "ProviderDashboard",
    # Keys
    "ProviderKeyManager",
    "SecureKeyStorage",
    "EnvironmentKeyResolver",
    # Router
    "SmartModelRouter",
    # Benchmark
    "ProviderBenchmark",
    # Wizard
    "FirstRunWizard",
    # Health
    "ProviderHealthMonitor",
    "ProviderHealthStatus",
    "HealthCheckResult",
    # Types
    "ProviderID",
    "ModelID",
    "SessionID",
    "RequestID",
    "APIKey",
    "ProviderType",
    "ProviderStatus",
    "ProviderCapability",
    "RoutingPolicy",
    "LoadBalancingStrategy",
    "RetryPolicy",
    "RateLimitStrategy",
    "HealthCheckStatus",
    "TaskType",
    "ProviderSettings",
    "ProviderMetadata",
    "ModelMetadata",
    "ProviderCapabilities",
    "RequestParameters",
    "UsageMetrics",
    "HealthMetrics",
    "BenchmarkMetrics",
    "ProviderDefinition",
    "ModelDefinition",
    "ProviderRequest",
    "ProviderResponse",
    "SessionState",
    "RoutingRule",
    "RetryConfig",
    "RateLimitConfig",
    "HealthCheckConfig",
    "BenchmarkConfig",
    "ProviderPlugin",
    "KeyStorageBackend",
    "HealthMonitor",
    "LoadBalancer",
    "FailoverManager",
    # Exceptions
    "ProviderRuntimeError",
    "ProviderError",
    "ProviderNotFoundError",
    "ProviderAlreadyExistsError",
    "ProviderInitializationError",
    "ProviderConnectionError",
    "ProviderTimeoutError",
    "ProviderCapabilityError",
    "ProviderDisabledError",
    "RequestError",
    "InvalidRequestError",
    "RequestTimeoutError",
    "RequestRateLimitedError",
    "RequestFailedError",
    "PluginError",
    "PluginNotFoundError",
    "PluginLoadError",
    "PluginInitializationError",
    "KeyError",
    "KeyNotFoundError",
    "InvalidKeyError",
    "KeyStorageError",
    "KeyEncryptionError",
    "RoutingError",
    "NoProviderAvailableError",
    "RoutingPolicyError",
    "LoadBalancingError",
    "HealthError",
    "HealthCheckError",
    "ProviderUnhealthyError",
    "RetryError",
    "MaxRetriesExceededError",
    "RateLimitError",
    "RateLimitExceededError",
    "SessionError",
    "SessionNotFoundError",
    "SessionExpiredError",
    "BenchmarkError",
    "BenchmarkFailedError",
    "ConfigurationError",
    "InvalidConfigurationError",
    "MissingConfigurationError",
    "SecurityError",
    "PermissionDeniedError",
    "InvalidInputError",
    "StreamingError",
    "StreamConnectionError",
    "StreamTimeoutError",
    # Constants
    "DEFAULT_PROVIDER_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_BASE_URL",
    "DEFAULT_PROVIDER_TYPE",
    "DEFAULT_MODEL_CONTEXT_LENGTH",
    "DEFAULT_MODEL_FAMILY",
    "DEFAULT_MODEL_SPEED",
    "DEFAULT_MODEL_QUALITY",
    "DEFAULT_RATE_LIMIT_REQUESTS",
    "DEFAULT_RATE_LIMIT_WINDOW",
    "DEFAULT_RATE_LIMIT_TOKENS",
    "DEFAULT_RATE_LIMIT_REFILL_RATE",
    "DEFAULT_RETRY_BASE_DELAY",
    "DEFAULT_RETRY_MAX_DELAY",
    "DEFAULT_RETRY_JITTER",
    "DEFAULT_HEALTH_CHECK_INTERVAL",
    "DEFAULT_HEALTH_CHECK_TIMEOUT",
    "DEFAULT_HEALTH_CHECK_MAX_FAILURES",
    "DEFAULT_HEALTH_CHECK_ENDPOINT",
    "DEFAULT_BENCHMARK_ITERATIONS",
    "DEFAULT_BENCHMARK_WARMUP_ITERATIONS",
    "DEFAULT_BENCHMARK_INPUT_SIZE",
    "DEFAULT_BENCHMARK_MAX_TOKENS",
    "DEFAULT_STORAGE_PATH",
    "DEFAULT_KEY_STORAGE_PATH",
    "DEFAULT_STATE_STORAGE_PATH",
    "TANGKU_PROVIDER_KEY_PREFIX",
    "TANGKU_PROVIDER_KEY_SUFFIX",
    "TANGKU_PROVIDER_DEFAULT_KEY",
    # Providers
    "OpenAIProvider",
    "AnthropicProvider",
    "GoogleProvider",
    "GroqProvider",
    "DeepSeekProvider",
    "MistralProvider",
    "CohereProvider",
    "TogetherAIProvider",
    "FireworksAIProvider",
    "AzureOpenAIProvider",
    "OpenRouterProvider",
    "OllamaProvider",
    "LMStudioProvider",
    "LocalModelProvider",
    "CustomProvider",
]


def __getattr__(name: str) -> Any:
    """Lazy-load modules to avoid circular imports."""
    module_map = {
        # Core Components
        "ProviderManager": (".manager", "ProviderManager"),
        "ProviderRegistry": (".registry", "ProviderRegistry"),
        "ProviderFactory": (".factory", "ProviderFactory"),
        "ProviderAdapter": (".adapter", "ProviderAdapter"),
        "ProviderSession": (".session", "ProviderSessionManager"),
        "ProviderHealth": (".health", "ProviderHealthMonitor"),
        "ProviderConfiguration": (".configuration", "ProviderConfiguration"),
        # Interfaces
        "ProviderRegistryInterface": (".interfaces", "ProviderRegistryInterface"),
        "ProviderManagerInterface": (".interfaces", "ProviderManager"),
        "ProviderAdapterInterface": (".interfaces", "ProviderAdapter"),
        "ProviderFactoryInterface": (".interfaces", "ProviderFactory"),
        "ProviderSessionInterface": (".interfaces", "ProviderSession"),
        "ProviderHealthInterface": (".interfaces", "ProviderHealth"),
        # Integration
        "BaseProviderAdapter": (".integration", "BaseProviderAdapter"),
        "HTTPProviderAdapter": (".integration", "HTTPProviderAdapter"),
        "ProviderCapabilityManager": (".integration", "ProviderCapabilityManager"),
        "ProviderAuthenticationManager": (".integration", "ProviderAuthenticationManager"),
        "ProviderConfigurationLoader": (".integration", "ProviderConfigurationLoader"),
        "ProviderSessionManager": (".integration", "ProviderSessionManager"),
        "ProviderConnectionManager": (".integration", "ProviderConnectionManager"),
        "ProviderRateLimitManager": (".integration", "ProviderRateLimitManager"),
        "ProviderUsageManager": (".integration", "ProviderUsageManager"),
        "ProviderStreamingManager": (".integration", "ProviderStreamingManager"),
        "ProviderRetryManager": (".integration", "ProviderRetryManager"),
        "RetryManager": (".integration", "RetryManager"),
        "RateLimiter": (".integration", "RateLimiter"),
        "CapabilityMatcher": (".integration", "CapabilityMatcher"),
        "ProviderSelector": (".integration", "ProviderSelector"),
        "ProviderRouter": (".integration", "ProviderRouter"),
        "FallbackManager": (".integration", "FallbackManager"),
        "LoadDistributionManager": (".integration", "LoadDistributionManager"),
        "CostAwareRouter": (".integration", "CostAwareRouter"),
        "LatencyAwareRouter": (".integration", "LatencyAwareRouter"),
        "HealthAwareRouter": (".integration", "HealthAwareRouter"),
        "ModelCatalogManager": (".integration", "ModelCatalogManager"),
        # Hub
        "ProviderHub": (".hub", "ProviderHub"),
        # Dashboard
        "ProviderDashboard": (".dashboard", "ProviderDashboard"),
        # Keys
        "ProviderKeyManager": (".keys", "ProviderKeyManager"),
        "SecureKeyStorage": (".keys", "SecureKeyStorage"),
        "EnvironmentKeyResolver": (".keys", "EnvironmentKeyResolver"),
        # Router
        "SmartModelRouter": (".router", "SmartModelRouter"),
        # Benchmark
        "ProviderBenchmark": (".benchmark", "ProviderBenchmark"),
        # Wizard
        "FirstRunWizard": (".wizard", "FirstRunWizard"),
        # Health
        "ProviderHealthMonitor": (".health", "ProviderHealthMonitor"),
        "ProviderHealthStatus": (".health", "ProviderHealthStatus"),
        "HealthCheckResult": (".health", "HealthCheckResult"),
        # Types
        "ProviderID": (".types", "ProviderID"),
        "ModelID": (".types", "ModelID"),
        "SessionID": (".types", "SessionID"),
        "RequestID": (".types", "RequestID"),
        "APIKey": (".types", "APIKey"),
        "ProviderType": (".types", "ProviderType"),
        "ProviderStatus": (".types", "ProviderStatus"),
        "ProviderCapability": (".types", "ProviderCapability"),
        "RoutingPolicy": (".types", "RoutingPolicy"),
        "LoadBalancingStrategy": (".types", "LoadBalancingStrategy"),
        "RetryPolicy": (".types", "RetryPolicy"),
        "RateLimitStrategy": (".types", "RateLimitStrategy"),
        "HealthCheckStatus": (".types", "HealthCheckStatus"),
        "TaskType": (".types", "TaskType"),
        "ProviderSettings": (".types", "ProviderSettings"),
        "ProviderMetadata": (".types", "ProviderMetadata"),
        "ModelMetadata": (".types", "ModelMetadata"),
        "ProviderCapabilities": (".types", "ProviderCapabilities"),
        "RequestParameters": (".types", "RequestParameters"),
        "UsageMetrics": (".types", "UsageMetrics"),
        "HealthMetrics": (".types", "HealthMetrics"),
        "BenchmarkMetrics": (".types", "BenchmarkMetrics"),
        "ProviderDefinition": (".types", "ProviderDefinition"),
        "ModelDefinition": (".types", "ModelDefinition"),
        "ProviderRequest": (".types", "ProviderRequest"),
        "ProviderResponse": (".types", "ProviderResponse"),
        "SessionState": (".types", "SessionState"),
        "RoutingRule": (".types", "RoutingRule"),
        "RetryConfig": (".types", "RetryConfig"),
        "RateLimitConfig": (".types", "RateLimitConfig"),
        "HealthCheckConfig": (".types", "HealthCheckConfig"),
        "BenchmarkConfig": (".types", "BenchmarkConfig"),
        "ProviderPlugin": (".types", "ProviderPlugin"),
        "KeyStorageBackend": (".types", "KeyStorageBackend"),
        "HealthMonitor": (".types", "HealthMonitor"),
        "LoadBalancer": (".types", "LoadBalancer"),
        "FailoverManager": (".types", "FailoverManager"),
        # Exceptions
        "ProviderRuntimeError": (".exceptions", "ProviderRuntimeError"),
        "ProviderError": (".exceptions", "ProviderError"),
        "ProviderNotFoundError": (".exceptions", "ProviderNotFoundError"),
        "ProviderAlreadyExistsError": (".exceptions", "ProviderAlreadyExistsError"),
        "ProviderInitializationError": (".exceptions", "ProviderInitializationError"),
        "ProviderConnectionError": (".exceptions", "ProviderConnectionError"),
        "ProviderTimeoutError": (".exceptions", "ProviderTimeoutError"),
        "ProviderCapabilityError": (".exceptions", "ProviderCapabilityError"),
        "ProviderDisabledError": (".exceptions", "ProviderDisabledError"),
        "RequestError": (".exceptions", "RequestError"),
        "InvalidRequestError": (".exceptions", "InvalidRequestError"),
        "RequestTimeoutError": (".exceptions", "RequestTimeoutError"),
        "RequestRateLimitedError": (".exceptions", "RequestRateLimitedError"),
        "RequestFailedError": (".exceptions", "RequestFailedError"),
        "PluginError": (".exceptions", "PluginError"),
        "PluginNotFoundError": (".exceptions", "PluginNotFoundError"),
        "PluginLoadError": (".exceptions", "PluginLoadError"),
        "PluginInitializationError": (".exceptions", "PluginInitializationError"),
        "KeyNotFoundError": (".exceptions", "KeyNotFoundError"),
        "InvalidKeyError": (".exceptions", "InvalidKeyError"),
        "KeyStorageError": (".exceptions", "KeyStorageError"),
        "KeyEncryptionError": (".exceptions", "KeyEncryptionError"),
        "NoProviderAvailableError": (".exceptions", "NoProviderAvailableError"),
        "RoutingPolicyError": (".exceptions", "RoutingPolicyError"),
        "LoadBalancingError": (".exceptions", "LoadBalancingError"),
        "HealthCheckError": (".exceptions", "HealthCheckError"),
        "ProviderUnhealthyError": (".exceptions", "ProviderUnhealthyError"),
        "MaxRetriesExceededError": (".exceptions", "MaxRetriesExceededError"),
        "RateLimitExceededError": (".exceptions", "RateLimitExceededError"),
        "SessionNotFoundError": (".exceptions", "SessionNotFoundError"),
        "SessionExpiredError": (".exceptions", "SessionExpiredError"),
        "BenchmarkFailedError": (".exceptions", "BenchmarkFailedError"),
        "InvalidConfigurationError": (".exceptions", "InvalidConfigurationError"),
        "MissingConfigurationError": (".exceptions", "MissingConfigurationError"),
        "PermissionDeniedError": (".exceptions", "PermissionDeniedError"),
        "InvalidInputError": (".exceptions", "InvalidInputError"),
        "StreamConnectionError": (".exceptions", "StreamConnectionError"),
        "StreamTimeoutError": (".exceptions", "StreamTimeoutError"),
        # Constants
        "DEFAULT_PROVIDER_TIMEOUT": (".constants", "DEFAULT_PROVIDER_TIMEOUT"),
        "DEFAULT_MAX_RETRIES": (".constants", "DEFAULT_MAX_RETRIES"),
        "DEFAULT_BASE_URL": (".constants", "DEFAULT_BASE_URL"),
        "DEFAULT_PROVIDER_TYPE": (".constants", "DEFAULT_PROVIDER_TYPE"),
        "DEFAULT_MODEL_CONTEXT_LENGTH": (".constants", "DEFAULT_MODEL_CONTEXT_LENGTH"),
        "DEFAULT_MODEL_FAMILY": (".constants", "DEFAULT_MODEL_FAMILY"),
        "DEFAULT_MODEL_SPEED": (".constants", "DEFAULT_MODEL_SPEED"),
        "DEFAULT_MODEL_QUALITY": (".constants", "DEFAULT_MODEL_QUALITY"),
        "DEFAULT_RATE_LIMIT_REQUESTS": (".constants", "DEFAULT_RATE_LIMIT_REQUESTS"),
        "DEFAULT_RATE_LIMIT_WINDOW": (".constants", "DEFAULT_RATE_LIMIT_WINDOW"),
        "DEFAULT_RATE_LIMIT_TOKENS": (".constants", "DEFAULT_RATE_LIMIT_TOKENS"),
        "DEFAULT_RATE_LIMIT_REFILL_RATE": (".constants", "DEFAULT_RATE_LIMIT_REFILL_RATE"),
        "DEFAULT_RETRY_BASE_DELAY": (".constants", "DEFAULT_RETRY_BASE_DELAY"),
        "DEFAULT_RETRY_MAX_DELAY": (".constants", "DEFAULT_RETRY_MAX_DELAY"),
        "DEFAULT_RETRY_JITTER": (".constants", "DEFAULT_RETRY_JITTER"),
        "DEFAULT_HEALTH_CHECK_INTERVAL": (".constants", "DEFAULT_HEALTH_CHECK_INTERVAL"),
        "DEFAULT_HEALTH_CHECK_TIMEOUT": (".constants", "DEFAULT_HEALTH_CHECK_TIMEOUT"),
        "DEFAULT_HEALTH_CHECK_MAX_FAILURES": (".constants", "DEFAULT_HEALTH_CHECK_MAX_FAILURES"),
        "DEFAULT_HEALTH_CHECK_ENDPOINT": (".constants", "DEFAULT_HEALTH_CHECK_ENDPOINT"),
        "DEFAULT_BENCHMARK_ITERATIONS": (".constants", "DEFAULT_BENCHMARK_ITERATIONS"),
        "DEFAULT_BENCHMARK_WARMUP_ITERATIONS": (".constants", "DEFAULT_BENCHMARK_WARMUP_ITERATIONS"),
        "DEFAULT_BENCHMARK_INPUT_SIZE": (".constants", "DEFAULT_BENCHMARK_INPUT_SIZE"),
        "DEFAULT_BENCHMARK_MAX_TOKENS": (".constants", "DEFAULT_BENCHMARK_MAX_TOKENS"),
        "DEFAULT_STORAGE_PATH": (".constants", "DEFAULT_STORAGE_PATH"),
        "DEFAULT_KEY_STORAGE_PATH": (".constants", "DEFAULT_KEY_STORAGE_PATH"),
        "DEFAULT_STATE_STORAGE_PATH": (".constants", "DEFAULT_STATE_STORAGE_PATH"),
        "TANGKU_PROVIDER_KEY_PREFIX": (".constants", "TANGKU_PROVIDER_KEY_PREFIX"),
        "TANGKU_PROVIDER_KEY_SUFFIX": (".constants", "TANGKU_PROVIDER_KEY_SUFFIX"),
        "TANGKU_PROVIDER_DEFAULT_KEY": (".constants", "TANGKU_PROVIDER_DEFAULT_KEY"),
        # Providers
        "OpenAIProvider": (".providers", "OpenAIProvider"),
        "AnthropicProvider": (".providers", "AnthropicProvider"),
        "GoogleProvider": (".providers", "GoogleProvider"),
        "GroqProvider": (".providers", "GroqProvider"),
        "DeepSeekProvider": (".providers", "DeepSeekProvider"),
        "MistralProvider": (".providers", "MistralProvider"),
        "CohereProvider": (".providers", "CohereProvider"),
        "TogetherAIProvider": (".providers", "TogetherAIProvider"),
        "FireworksAIProvider": (".providers", "FireworksAIProvider"),
        "AzureOpenAIProvider": (".providers", "AzureOpenAIProvider"),
        "OpenRouterProvider": (".providers", "OpenRouterProvider"),
        "OllamaProvider": (".providers", "OllamaProvider"),
        "LMStudioProvider": (".providers", "LMStudioProvider"),
        "LocalModelProvider": (".providers", "LocalModelProvider"),
        "CustomProvider": (".providers", "CustomProvider"),
    }

    if name not in module_map:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module_name, attr_name = module_map[name]
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
