"""Trigger system architecture for Tangku AgentOS."""

from .interfaces import (
    APITrigger,
    AgentTrigger,
    FileTrigger,
    GitTrigger,
    MemoryTrigger,
    SystemTrigger,
    TimeTrigger,
    TriggerManagerInterface,
    TriggerRegistryInterface,
    Trigger,
    TriggerContext,
    TriggerResult,
    Trigger,
    TriggerContext,
    TriggerResult,
    Trigger,
    TriggerContext,
    TriggerResult,
    Trigger,
    TriggerContext,
    TriggerResult,
    Trigger,
    TriggerContext,
    TriggerResult,
    Trigger,
    TriggerContext,
    TriggerResult,
    Trigger,
    TriggerContext,
    TriggerResult,
    UserTrigger,
    WebhookTrigger,
    WorkflowTrigger,
)
from .manager import TriggerManager
from .registry import TriggerRegistry
from .models import Trigger, TriggerContext, TriggerResult

__all__ = [
    "TriggerManager",
    "TriggerRegistry",
    "TriggerManagerInterface",
    "TriggerRegistryInterface",
    "FileTrigger",
    "GitTrigger",
    "TimeTrigger",
    "WebhookTrigger",
    "APITrigger",
    "WorkflowTrigger",
    "AgentTrigger",
    "MemoryTrigger",
    "UserTrigger",
    "SystemTrigger",
    "Trigger",
    "TriggerContext",
    "TriggerResult",
]
