"""Repository intelligence architecture for Tangku AgentOS."""

from .interfaces import (
    BranchManager as BranchManagerInterface,
    CommitManager as CommitManagerInterface,
    IssueManager,
    MergeManager as MergeManagerInterface,
    PullRequestManager,
    ReleaseManager,
    RepositoryManagerInterface,
    RepositoryRegistryInterface,
    RepositoryScanner,
    TagManager,
    VersionManager,
)
from .manager import (
    BranchManager,
    ChangeManager,
    CollaborationManager,
    CommitManager,
    DiffManager,
    GitManager,
    MergeManager,
    RepositoryManager,
    VersionControlManager,
)
from .registry import RepositoryRegistry
from .models import (
    Branch,
    BranchLifecycle,
    BranchMetadata,
    ChangeHistory,
    ChangeMetadata,
    Commit,
    CommitGraph,
    CommitHistory,
    CommitMetadata,
    ConflictMetadata,
    DiffContext,
    DiffMetadata,
    Issue,
    MergeContext,
    MergeMetadata,
    PullRequest,
    Release,
    Repository,
    RepositoryConfiguration,
    RepositoryContext,
    RepositoryHealth,
    RepositoryLifecycle,
    RepositoryMetadata,
    RepositoryPermissions,
    RepositorySession,
    RepositoryStatistics,
    RepositoryType,
    ReviewMetadata,
    ReviewSession,
    Version,
    VersionControlMetadata,
)

__all__ = [
    "RepositoryManager",
    "RepositoryManagerInterface",
    "RepositoryRegistry",
    "RepositoryRegistryInterface",
    "RepositoryScanner",
    "BranchManager",
    "CommitManager",
    "GitManager",
    "MergeManager",
    "ChangeManager",
    "CollaborationManager",
    "DiffManager",
    "VersionControlManager",
    "Repository",
    "RepositoryMetadata",
    "RepositoryType",
    "RepositoryContext",
    "RepositorySession",
    "RepositoryLifecycle",
    "RepositoryConfiguration",
    "RepositoryStatistics",
    "RepositoryHealth",
    "VersionControlMetadata",
    "Branch",
    "BranchMetadata",
    "BranchLifecycle",
    "Commit",
    "CommitMetadata",
    "CommitHistory",
    "CommitGraph",
    "ChangeMetadata",
    "ChangeHistory",
    "MergeMetadata",
    "MergeContext",
    "ConflictMetadata",
    "DiffMetadata",
    "DiffContext",
    "Issue",
    "PullRequest",
    "Release",
    "Version",
    "ReviewMetadata",
    "ReviewSession",
    "RepositoryPermissions",
]
